#!/bin/sh
# husky

# Created by Husky v4.2.5 (https://github.com/typicode/husky#readme)
#   At: 2020-6-21 16:58:07
#   From: undefined (https://github.com/typicode/husky#readme)

. "$(dirname "$0")/husky.sh"
